[package]
name = "conum"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "An implementation of big numbers, specified by arbitrary digit widths"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
